### ISSUE TITLE
Hey, Let's Connect? Rahul this side

### ISSUE THREAD

**Issue by ramped-fire** [AdarshRawat1/AdarshRawat1#1]
he adarsh, wanted to ask you if you are open for junior level roles as fullstack dev? would love to speak as we are hiring. can you drop me a hi on telegram @ rudeus8055 ?

**Comment by AdarshRawat1** [comment]
Sure, here is my [LinkedIn profile](https://www.linkedin.com/in/adarsh-rawat/) lets connect.
